# SPDX-License-Identifier: MIT-0
---
# Create volumes from vars
- name: Create volume(s) on NeCTAR
  openstack.cloud.volume:
    cloud: "{{ cloud }}"
    auth:
      project_name: "{{ project_name }}"
    display_name: "{{ item.1.vol_name_prefix }}@{{ item.0.name }}"
    size: "{{ item.1.vol_size }}"
    availability_zone: "{{ availability_zone }}"
    wait: true
    timeout: 600
    state: present
  loop: "{{ lookup('subelements', instances, 'volumes', {'skip_missing': True}) }}"
  register: os_vol

# # Get a list of volume Ids from the return value of os_volume
# - name: Create a list of volume Ids
#   ansible.builtin.set_fact:
#     os_vol_ids: "{{ os_vol_ids|default([]) + [ item.id ] }}"
#   loop: "{{ os_vol.results }}"

# - ansible.builtin.debug:
#     msg: "Volume {{ os_vol_ids }} has been created."
